services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: chatpulse-backend
      env_file:
        - ./backend/.env
      environment:
        PORT: 5000
        NODE_ENV: development
      ports:
        - "5000:5000"
      command: npm run dev
      develop:
        watch:
          - action: sync+restart     # ← sync files then restart nodemon
            path: ./backend/src
            target: /app/src
            ignore:
              - node_modules/
          - action: sync+restart
            path: ./backend/config
            target: /app/config
            ignore:
              - node_modules/
          - action: rebuild          # ← full image rebuild if deps change
            path: ./backend/package.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatpulse-frontend
    environment:
      VITE_API_PROXY_TARGET: http://chatpulse-backend:5000
      VITE_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync             # 3. Explicitly sync config files if they change
          path: ./frontend/vite.config.js
          target: /app/vite.config.js
        - action: rebuild
          path: ./frontend/package.json

